[package]
name = "ch9-clock0"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = "2"


[target.'cfg(windows)'.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"

[target.'cfg(not(windwos))'.dependencies]
libc = "0.2"
