[package]
name = "ch9_clock2"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
chrono = "0.4.39"
clap = "2"


[target.'cfg(windows)'.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"

[target.'cfg(not(windwos))'.dependencies]
libc = "0.2"

